export const AppEventType = {
  NOTIFICATION_RELOAD: 'NOTIFICATION_RELOAD',
  NOTIFICATION_REFRESH: 'NOTIFICATION_REFRESH',
  SURVEY_TOGGLE_VISIBILITY: 'SURVEY_TOGGLE_VISIBILITY',
  SURVEY_DELETED: 'SURVEY_DELETED',
  SURVEY_UPDATED: 'SURVEY_UPDATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  SURVEY_BIN_RESTORED: 'SURVEY_BIN_RESTORED',
  USER_SETTINGS_UPDATED: 'USER_SETTINGS_UPDATED',
  UPDATE_NICKNAME_UPDATED: 'UPDATE_NICKNAME_UPDATED',
  ORGANIZATION_SETTINGS_UPDATED: 'ORGANIZATION_SETTINGS_UPDATED',
} as const;
export type AppEventType = (typeof AppEventType)[keyof typeof AppEventType];

export type AppEvent = { type: AppEventType; payload?: any };
